service: backend
app: backend
org: gregtrifan
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    DYNAMODB_NAMESPACE: ${opt:stage, "dev"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-plugin-monorepo
  - serverless-offline
package:
  individually: true
  exclude:
    - test/**
    - coverage/**
functions:
  uploadGame:
    handler: src/Game/upload.handler
    events:
      - http:
          method: POST
          path: /api/game
          cors: true
          request:
            schemas:
              application/json: ${file(models/upload-game-model.json)}

  getGames:
    handler: src/Game/list.handler
    events:
      - http:
          method: GET
          path: /api/games/{page}
          cors: true

  getGame:
    handler: src/Game/get.handler
    events:
      - http:
          method: GET
          path: /api/game/{session}
          cors: true

  getPlayer:
    handler: src/Players/get.handler
    events:
      - http:
          method: GET
          path: /api/player/{player}
          cors: true

  listPlayers:
    handler: src/Players/list.handler
    events:
      - http:
          method: GET
          path: /api/players
          cors: true
  listLoserPlayers:
    handler: src/Players/list-losers.handler
    events:
      - http:
          method: GET
          path: /api/losers
          cors: true

custom:
  # serverless offline plugin setup
  serverless-offline:
    httpPort: 4000
  dynamodb:
    stages:
      - "dev"
      - "test"
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
resources:
  Resources:
    GamesDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: realworld-${self:provider.environment.DYNAMODB_NAMESPACE}-games

    PlayersDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
          - AttributeName: wins
            AttributeType: N
          - AttributeName: losses
            AttributeType: N
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: realworld-${self:provider.environment.DYNAMODB_NAMESPACE}-players
        GlobalSecondaryIndexes:
          - IndexName: winners
            KeySchema:
              - AttributeName: wins
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: losers
            KeySchema:
              - AttributeName: losses
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
